# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# This will however be taken care of via grunt watch file

# Site settings
title: Corporate Programmer
email: hello@corporateprogrammer.com
description: >
  A survival guide for corporate software developers.
keywords: corporate, programmer, software developer, survival guide, company, businesses, happiness, clarice bouwer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.corporateprogrammer.com" # the base hostname & protocol for your site
author:
  name: Clarice Bouwer
  email: hello@corporateprogrammer.com
  twitter: https://www.twitter.com/cbillowes

build: debug

# Build settings
markdown: kramdown
permalink: /blog/:title/
exclude:
  - node_modules
  - _assets #grunt will take care of this.

#Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: /blog/page/:num/
